output_dir: "output" # Default
input_dir: "input" # Default
supplement_dir: "supplement" # Store blacklist files if being used
# mapq: 30 # This would filter .bam, .crai, .bed files to a minimum mapq score of 30. However, this is redundant given the following finaletoolkit operation.
blacklist: "blacklist.bed"
use_finaletoolkit: True # For now, enables simply the frag-length-bins features

# Frag-length-bins parameters
frag_length_bins_mapq: 30
frag_length_bins_bin_size: 10
frag_length_bins_min_len: 50
frag_length_bins_max_len: 350
frag_length_bins_chrom: "22"
frag_length_bins_start: 40000000
frag_length_bins_end: 41000000
