output_dir: "output" # Default
input_dir: "input" # Default
supplement_dir: "supplement" # Store blacklist files if being used
mapq: 35 # Filter .bam, .crai, .bed files to a minimum mapq score of 35. 
blacklist: "blacklist.bed" # Located in the supplement/ directory. Removes intervals where the midpoints are within the bounds of blacklisted intervals.
use_finaletoolkit: True # For now, enables simply the frag-length-bins feature

# Frag-length-bins parameters
frag_length_bins_bin_size: 10
frag_length_bins_min_len: 50
frag_length_bins_max_len: 350
# frag_length_bins_chrom: "22"
# frag_length_bins_start: 10031
# frag_length_bins_end: 225368645
